In [1]:
import numpy as np

arr = np.random.randint(1, 100, size=(10,5)) # sample(row) - 10, feature(column) - 5

In [44]:
arr

array([[25, 45, 77, 78, 72],
       [33, 70, 58, 72, 28],
       [26, 32, 75, 34, 89],
       [67, 81, 76, 43, 29],
       [ 8, 23, 71, 99,  5],
       [45, 61, 25, 57, 77],
       [31, 80, 47, 83, 33],
       [13, 30, 81, 17, 29],
       [84, 19, 62, 48, 19],
       [85, 70, 65, 79, 48]], dtype=int32)

In [45]:
arr.shape

(10, 5)

In [46]:
b = arr.reshape(2, 25)

print(b.shape)
b.ndim

(2, 25)


2

In [47]:
b

array([[25, 45, 77, 78, 72, 33, 70, 58, 72, 28, 26, 32, 75, 34, 89, 67,
        81, 76, 43, 29,  8, 23, 71, 99,  5],
       [45, 61, 25, 57, 77, 31, 80, 47, 83, 33, 13, 30, 81, 17, 29, 84,
        19, 62, 48, 19, 85, 70, 65, 79, 48]], dtype=int32)

In [48]:
flatten = arr.flatten()
print(flatten.ndim)
flatten

1


array([25, 45, 77, 78, 72, 33, 70, 58, 72, 28, 26, 32, 75, 34, 89, 67, 81,
       76, 43, 29,  8, 23, 71, 99,  5, 45, 61, 25, 57, 77, 31, 80, 47, 83,
       33, 13, 30, 81, 17, 29, 84, 19, 62, 48, 19, 85, 70, 65, 79, 48],
      dtype=int32)

In [49]:
column_wise_flattening = np.ravel(arr, order = 'F')
# F = fortran code in fortran language array store in memory column by column
# C = c code in c-programing language array store in memory row by row
print(column_wise_flattening.ndim)
column_wise_flattening

1


array([25, 33, 26, 67,  8, 45, 31, 13, 84, 85, 45, 70, 32, 81, 23, 61, 80,
       30, 19, 70, 77, 58, 75, 76, 71, 25, 47, 81, 62, 65, 78, 72, 34, 43,
       99, 57, 83, 17, 48, 79, 72, 28, 89, 29,  5, 77, 33, 29, 19, 48],
      dtype=int32)

In [29]:
a = np.random.randint(1,10, size=(2,3))
b = np.random.randint(20,30, size=(1,3))

print(f"array a :\n{a}")
print(f"array b :\n{b}")

array a :
[[6 9 3]
 [3 6 2]]
array b :
[[22 28 28]]


### concatenate

In [30]:
# For row-wise concatenation, c = c (must be)
con_row = np.concatenate((a,b), axis=0) # row wise
print(f"row wise concatenate :\n{con_row}")

#For column-wise concatenation, r = r (must be)
con_col = np.concatenate((a,b), axis = 1) # column wise
print(f"column wise concatenate :\n{con_col}")

row wise concatenate :
[[ 6  9  3]
 [ 3  6  2]
 [22 28 28]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [65]:
# transpose
mat = np.array([[10, 20, 30],
              [30, 40, 50]
              ])
print(mat,"\n")
transpose = mat.T
transpose

[[10 20 30]
 [30 40 50]] 



array([[10, 30],
       [20, 40],
       [30, 50]])

In [75]:
# array split

a = np.random.randint(1, 10, size = (9, ))
print(a)

splitted_array = np.array_split(a,4)
print(splitted_array)

# split -> equal division
splitted_array = np.split(a,4)
splitted_array

[1 1 1 7 6 8 4 9 4]
[array([1, 1, 1], dtype=int32), array([7, 6], dtype=int32), array([8, 4], dtype=int32), array([9, 4], dtype=int32)]


ValueError: array split does not result in an equal division

### arithmetic operator and mathematical functions

In [4]:
x = np.array([10, 20, 30, 40])
y = np.array([2, 3, 4, 5])

add = x+y # or np.add(x+y)
print(add)

sub = x - y
print(sub)

mult = x*y
print(mult)

div = x/y
print(div)

remainder = x % y

print(remainder)

[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [20]:
# mathematical function

# trigonometry

# sin, cos, tan take values in radians
sin_val = np.sin(x)
print(sin_val)

deg_con = np.rad2deg(x) # r = theta * (pi/10) and Deg = r * (180/pi)
print(deg_con)

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]


In [22]:
# log

base_10_log_val = np.log10(x) # x/bse to x=1 how many times
print(x)
base_10_log_val

[10 20 30 40]


array([1.        , 1.30103   , 1.47712125, 1.60205999])

In [23]:
#square root
sqrt = np.sqrt(x)
sqrt

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [9]:
print(x)

s = np.sum(x)
print(s)

#prefix sum

cumul = np.cumulative_sum(x)
print(cumul)

[10 20 30 40]
100
[ 10  30  60 100]


In [14]:
# comparison - >, <, >=, <=, ==, !=

import numpy as np

x = np.array([10, 20, 30, 40])
y = np.array([2, 3, 4, 40])

greater_than = x > y
print(greater_than)

less_than = x < y
print(less_than)

greater_than_equal = x >= y
print(greater_than_equal)

less_than_equal = x <= y
print(less_than_equal)

equal = x == y
print(equal)

not_equal = x != y
print(not_equal)

print(np.all(greater_than))

print(np.any(equal))

[ True  True  True False]
[False False False False]
[ True  True  True  True]
[False False False  True]
[False False False  True]
[ True  True  True False]
False
True


### Sorting

In [3]:

x = np.array([10, 8, 16, 100])

z = x.copy()

In [4]:
#inplace

z.sort()

print(x)

print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [27]:
# copy sorting

sort_arr = np.sort(x)

print(sort_arr)

print(x)

[  8  10  16 100]
[ 10   8  16 100]


In [47]:
# 2d array sorting
mat = np.array ([[10, 3, 5], [8, 4, 9]])

#horizon axis = 1, colum wise

hor_sort = np.sort(mat, axis=1)
print(hor_sort)

#vertical axis = 0, row wise

vart_sort = np.sort(mat, axis=0)
print(vart_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


### Searching

In [48]:
print(x)

[ 10   8  16 100]


In [49]:
# np.where(condition, x, y) if ture x=x, otherwise replace x with y

# For 1d
idx = np.where(x==8) # # returns index column[x1,x2,...x]
print(idx)

y = np.where(x > 8, x, 0) # returns array after update
print(y)

(array([1]),)
[ 10   0  16 100]


In [50]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [52]:
print(mat)
# For 2d
idx = np.where(mat > 8) # returns index row[y1,y2,...y], column[x1,x2,...x]
print(idx)

y = np.where(mat > 8, mat, 0) # returns array after update
print(y)

[[10  3  5]
 [ 8  4  9]]
(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [53]:
# For 3d array
three_d = np.array ([
    [
        [10,  3,  5],
        [ 8,  4,  9]
    ],
    [
        [10, 20, 30],
        [30, 40, 50]
    ]
])
idx = np.where(three_d > 8) # returns index depth[z1,z2,...z], row[y1,y2,...y], column[x1,x2,...x]
print(idx)

y = np.where(three_d > 8, three_d, 0) # returns array after update
print(y)

(array([0, 0, 1, 1, 1, 1, 1, 1]), array([0, 1, 0, 0, 0, 1, 1, 1]), array([0, 2, 0, 1, 2, 0, 1, 2]))
[[[10  0  0]
  [ 0  0  9]]

 [[10 20 30]
  [30 40 50]]]


In [56]:
# min max idx searching
x = np.array([10, 100, 16, 100])

max_val_idx = np.argmax(x)
min_val_idx = np.argmin(x)

print(max_val_idx)
print(min_val_idx)

1
0


### counting in ndarray

In [58]:
a = np.random.randint(1,100, size=100)
print(a)

[78 36 11 46 36 76 42 21 20 70 37 56 87 39 79 12 45 30 99 72 25 62 44 71
 94 83 93 85 77 44 89 42 23 75 67 88 53 72 68 52 66 55 12 72 98 60 58 38
 14 61 21 19 95 18 90 41 24 82 27 17 79 44 69 44 27 70 43 32 20  3 68 35
 29 19 27 75 50 87 65 21 70 25 81 99 45 37 46 87 68 30 21 82 67 11 16 70
  2 21 17 40]


In [59]:
val_greater_than_60 = np.count_nonzero(a > 60)

print(val_greater_than_60)

42


In [63]:
unique_val = np.unique(a)
print(unique_val)
print("\n")
unique_with_count = np.unique(a, return_counts = True)

print(unique_with_count)
print("\n")

unique_val, count = np.unique(a, return_counts = True)

print(unique_val)
print("\n")
print(count)

[ 2  3 11 12 14 16 17 18 19 20 21 23 24 25 27 29 30 32 35 36 37 38 39 40
 41 42 43 44 45 46 50 52 53 55 56 58 60 61 62 65 66 67 68 69 70 71 72 75
 76 77 78 79 81 82 83 85 87 88 89 90 93 94 95 98 99]


(array([ 2,  3, 11, 12, 14, 16, 17, 18, 19, 20, 21, 23, 24, 25, 27, 29, 30,
       32, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 50, 52, 53, 55,
       56, 58, 60, 61, 62, 65, 66, 67, 68, 69, 70, 71, 72, 75, 76, 77, 78,
       79, 81, 82, 83, 85, 87, 88, 89, 90, 93, 94, 95, 98, 99],
      dtype=int32), array([1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 5, 1, 1, 2, 3, 1, 2, 1, 1, 2, 2, 1,
       1, 1, 1, 2, 1, 4, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1,
       4, 1, 3, 2, 1, 1, 1, 2, 1, 2, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2]))


[ 2  3 11 12 14 16 17 18 19 20 21 23 24 25 27 29 30 32 35 36 37 38 39 40
 41 42 43 44 45 46 50 52 53 55 56 58 60 61 62 65 66 67 68 69 70 71 72 75
 76 77 78 79 81 82 83 85 87 88 89 90 93 94 95 98 99]


[1 1 2 2 1 1 2 1 2 2 5 1 1 2 3 1 2 1 1 2 2 1 1 1 1 2 1 4 2 2 1 1 1 1

### statistical function

In [18]:
# data load
import numpy as np

data = np.genfromtxt('student_scores.csv' , delimiter =',', skip_header = 1)

print(data,"\n")

#slicing data
math_marks = data[::,:1]

print(math_marks.T)

mx_math_marks = np.max(math_marks)
mn_math_marks = np.min(math_marks)
average_math_marks = np.mean(math_marks)
median_math_marks = np.median(math_marks)

print(f"max_math_marks: {mx_math_marks}\n")
print(f"min_math_marks: {mn_math_marks}\n")
print(f"average_math_marks: {average_math_marks}\n")
print(f"median_math_marks: {median_math_marks}\n")

#standard deviation

# Step 1: Find difference from average for each value
# Step 2: Find average of all squared differences
# Step 3: Take square root


std_math_marks = np.std(math_marks)

print(std_math_marks,'\n')

Lower_bound = average_math_marks - std_math_marks
Upper_bound = average_math_marks + std_math_marks

print("\n--- Performance Categories ---")
print(f"{'Poor Marks:':<20} < {Lower_bound:.2f}")
print(f"{'Average Marks:':<20} {Lower_bound:.2f} - {Upper_bound:.2f}")
print(f"{'Higher Marks:':<20} > {Upper_bound:.2f}\n")

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]] 

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
max_math_marks: 95.0

min_math_marks: 45.0

average_math_marks: 73.15

median_math_marks: 73.5

13.788672887555204 


--- Performance Categories ---
Poor Marks:          < 59.36
Average Marks:       59.36 - 86.94
Higher Marks:        > 86.94



In [30]:

study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

r = np.corrcoef(data)

# Pearson Correlation Coefficient Formula
# 
# r = Σ(xi - x̄)(yi - ȳ) / √[Σ(xi - x̄)² × Σ(yi - ȳ)²]
#
# Where:
#   r = correlation coefficient (ranges from -1 to +1)
#   xi, yi = individual data points
#   x̄, ȳ = means(average) of x and y
#   Σ = summation (sum all values)
#   n = number of data points
#
# Numerator: Covariance (how much x and y move together)
# Denominator: Product of standard deviations (normalizes the value)
#
# Interpretation:
#   r ≈ 1.0  → Strong positive correlation
#   r ≈ -1.0 → Strong negative correlation
#   r ≈ 0.0  → No correlation

r_rounded = np.round(r, 4)

print(f"Correlation between study hours and exam scores: {r_rounded}")

Correlation between study hours and exam scores: [[1.     0.9986]
 [0.9986 1.    ]]


## linear algebra

In [33]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# A = r1 x c1 , B = r2 x c2
# if c1 = r2 then A x B = possible = r1 x c2
dot_product = np.dot(A, B)

print(dot_product)     

#trace
print(np.trace(dot_product))

[[ 58  64]
 [139 154]]
212


In [42]:
# determinant of matrix
sq_mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

det_of_sq = np.linalg.det(sq_mat)

print(det_of_sq)


6.66133814775094e-16
2


In [ ]:
# rank of matrix
rank_sq = np.linalg.matrix_rank(sq_mat)

print(rank_sq)

In [51]:
np.sin(np.pi/2)

np.float64(1.0)

In [54]:
a = np.array([1,2,3])
b = np.array([1,2,3])
a+b

array([2, 4, 6])

In [3]:
import numpy s np

A = np.array([
 [6, 1, 3, 8],
 [4, 2, 6, -1],
 [10, 3, 9, 7],
 [16, 4, 12, 15]
])

print(np.linalg.matrix_rank(A))

2
