In [69]:
import numpy as np

#dataset
data = np.array([
    [9.5, 0.5, 95.5],
    [8.2, 1.2, 86.4],
    [7.8, 1.5, 82.1],
    [7.0, 1.0, 81.0],
    [6.5, 2.0, 73.5],
    [5.0, 1.5, 70.0],
    [4.5, 3.0, 60.5],
    [3.0, 2.5, 55.0],
    [2.0, 4.0, 44.0],
    [1.5, 4.5, 39.5]
])

print(data)            

[[ 9.5  0.5 95.5]
 [ 8.2  1.2 86.4]
 [ 7.8  1.5 82.1]
 [ 7.   1.  81. ]
 [ 6.5  2.  73.5]
 [ 5.   1.5 70. ]
 [ 4.5  3.  60.5]
 [ 3.   2.5 55. ]
 [ 2.   4.  44. ]
 [ 1.5  4.5 39.5]]


In [26]:
# randomizing the dataset

random_idx = np.random.choice(10, size=(10,), replace = False)
print(random_idx)
# data = data[[7, 2, 9, 0, 5, 3, 1, 8, 4, 6]]
data = data[random_idx]

data

[3 0 7 1 4 5 2 8 9 6]


array([[ 9.5,  0.5, 95.5],
       [ 5. ,  1.5, 70. ],
       [ 1.5,  4.5, 39.5],
       [ 4.5,  3. , 60.5],
       [ 7.8,  1.5, 82.1],
       [ 7. ,  1. , 81. ],
       [ 2. ,  4. , 44. ],
       [ 6.5,  2. , 73.5],
       [ 8.2,  1.2, 86.4],
       [ 3. ,  2.5, 55. ]])

In [71]:
# feature(x), target(y) extraction

x = data[ : , : 2]
y = data[ : , 2: ]
x

array([[9.5, 0.5],
       [8.2, 1.2],
       [7.8, 1.5],
       [7. , 1. ],
       [6.5, 2. ],
       [5. , 1.5],
       [4.5, 3. ],
       [3. , 2.5],
       [2. , 4. ],
       [1.5, 4.5]])

In [74]:
# train, test split

train_idx = int(len(data) * (80/100))
x_train = x[: train_idx]
y_train = y[ : train_idx]

x_test = x[ train_idx : ]
y_test = y[ train_idx : ]

In [75]:
# doing this work more easily
from sklearn.model_selection import train_test_split

# feature(x), target(y) extraction

x = data[ : , : 2]
y = data[ : , 2: ]

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.2) # beacuse 20% = 20/100 = 0.2
print(x)
print(f"x_train\n{x_train}")
print(f"x_test\n{x_test}")

[[9.5 0.5]
 [8.2 1.2]
 [7.8 1.5]
 [7.  1. ]
 [6.5 2. ]
 [5.  1.5]
 [4.5 3. ]
 [3.  2.5]
 [2.  4. ]
 [1.5 4.5]]
x_train
[[1.5 4.5]
 [9.5 0.5]
 [5.  1.5]
 [3.  2.5]
 [7.  1. ]
 [2.  4. ]
 [4.5 3. ]
 [6.5 2. ]]
x_test
[[8.2 1.2]
 [7.8 1.5]]
