## Practice Problem (Array dimension using numpy)

### 1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.

In [2]:
import numpy as np

# 1d array

array_1d = np.array([1, 2, 3, 4])

# 2d arraay
array_2d = np.array(
    [
        [1, 2, 3, 4], # 1st 1d
        [1, 2, 3, 4] # 2nd 1d
    ]
)

array_2d1 = np.array([array_1d, array_1d])

# 3d array
array_3d = np.array(
    [
        [[1, 2, 3, 4], [1, 2, 3, 4]], #1st 2d
        [[1, 2, 3, 4], [1, 2, 3, 4]] #2nd 2d
    ]
)

array_3d1 = np.array([array_2d, array_2d])

print(" 1 D array")
print(array_1d.shape)
print(array_1d.ndim)
print(array_1d, "\n")

print(" 2 D array")
print(array_2d.shape)
print(array_2d.ndim)
print(array_2d1.shape)
print(array_2d1.ndim)
print(array_2d, "\n\n", array_2d1, "\n\n")

print(" 3 D array")
print(array_3d.shape)
print(array_3d.ndim)
print(array_3d1.shape)
print(array_3d1.ndim)
print(array_3d, "\n\n", array_3d1)

 1 D array
(4,)
1
[1 2 3 4] 

 2 D array
(2, 4)
2
(2, 4)
2
[[1 2 3 4]
 [1 2 3 4]] 

 [[1 2 3 4]
 [1 2 3 4]] 


 3 D array
(2, 2, 4)
3
(2, 2, 4)
3
[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]] 

 [[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]


### 2 . Create:

In [7]:
# an array of zeros of shape (3,3)
zeros_array = np.zeros((3,3))

# an array of ones of shape (2,5)
ones_array = np.ones((2,5))

# an array filled with 7
sevens_array = np.full((3,3),7)

print(zeros_array, '\n')
print(ones_array, '\n')
print(sevens_array, '\n')

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[7 7 7]
 [7 7 7]
 [7 7 7]] 



### 3 . Create an array of even numbers between 10 and 50 using arange.


In [14]:
array_range = np.arange(10, 51, 2)

array_range

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

### 3 . Create an array of even numbers between 10 and 50 using arange.

In [22]:
matrix = np.random.randint(0, 16, size=(4,4))

print(matrix, '\n')

# Extract first row
first_row = matrix[0]
print(first_row, '\n')

# Extract  last column
last_column = matrix[:, 3]
print(last_column, '\n')

# Extract a 2×2 subarray from the cente

center = matrix[1:3, 1:3]
print(center)

[[14  0  1 14]
 [ 9 10 14  8]
 [ 0  7  1 14]
 [ 8 11  4  4]] 

[14  0  1 14] 

[14  8 14  4] 

[[10 14]
 [ 7  1]]
